ABREVIACIONES = {
    "adv. m": "Adverbio Masculino",
    "adv. m. interrog": "Adverbio Masculino Interrogativo",
    "contr": "Contracción de la preposición + artículo",
    "pron": "Pronombre",
    "conj": "Conjunción",
    "adj": "Adjetivo",
    "adj. col": "Adjetivo (Uso Coloquial)",
    "art": "Artículo",
    "interj": "Interjección",
    "m": "Nombre Masculino",
    "f": "Nombre Femenino",
    "v": "Verbo",
    "p. p. irreg": "Verbo del Participio del Presente Irregular",
    "tr": "Verbo Transitivo",
    "tr. mat": "Verbo Transitivo uso Matematicas",
    "tr. e intr": "Verbo Transitivo e Verbo Intrasitivo",
    "intr": "Verbo Intrasitivo",
    "cop": "Verbo Copulativo",
    "intr. col": "Verbo Intransitivo (Uso Coloquial)",
    "suf": "Sufijo",
    "pref": "Prefijo"
}
